import { getLayout as getPageTitleLayout } from 'src/layouts/page-title';
import { getLayout as getMainLayout } from 'src/layouts/main';

const TemplatePage = () => {
    return (
        <div style={{ height: '100vh' }}>
            <div className="hero">
                <div className="hero-body">
                    <div className="container">
                        <h1 className="title">This template page was auto generated by generate_template script</h1>
                    </div>
                </div>
            </div>
        </div>
    );
};

TemplatePage.getLayout = page => getPageTitleLayout(getMainLayout(page), 'Template Page');

export default TemplatePage;
